# **Variance Analysis**

# **Import the Libraries and the Data Set**

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import chardet
plt.style.use("seaborn-v0_8-whitegrid")
import warnings
warnings.filterwarnings('ignore')

In [4]:
sales = pd.read_csv("/content/sales BSA.csv")

In [27]:
budget =pd.read_excel("/content/budget.xlsx")

# **Data understanding**

In [6]:
sales

,ProductKey,OrderDate,ShipDate,CustomerKey,PromotionKey,SalesTerritoryKey,SalesOrderNumber,SalesOrderLineNumber,OrderQuantity,UnitPrice,...,Total sales revenue,Unnamed: 16,Unnamed: 17,Gross Profit,Unnamed: 19,StandardCost,List Price,Unnamed: 22,diif std cost,diff list price
0,310,01-01-2014 00:00,08-01-2014 00:00,21768,1,6,SO43697,1.0,2.0,1789.1350,...,3578.2700,0.0,NaN,-764.3184,NaN,2171.2942,3578.2700,NaN,0.0,0.0
1,346,01-01-2014 00:00,08-01-2014 00:00,28389,1,7,SO43698,1.0,2.0,1699.9950,...,3399.9900,0.0,NaN,-424.3188,NaN,1912.1544,3399.9900,NaN,0.0,0.0
2,346,01-01-2014 00:00,08-01-2014 00:00,25863,1,1,SO43699,1.0,2.0,1699.9950,...,3399.9900,0.0,NaN,-424.3188,NaN,1912.1544,3399.9900,NaN,0.0,0.0
3,336,01-01-2014 00:00,08-01-2014 00:00,14501,1,4,SO43700,1.0,2.0,349.5491,...,699.0982,0.0,NaN,-127.1944,NaN,413.1463,699.0982,NaN,0.0,0.0
4,346,01-01-2014 00:00,08-01-2014 00:00,11003,1,9,SO43701,1.0,2.0,1699.9950,...,3399.9900,0.0,NaN,-424.3188,NaN,1912.1544,3399.9900,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49167,479,12-11-2016 00:00,19-11-2016 00:00,21959,1,9,SO70377,2.0,1.0,8.9900,...,8.9900,0.0,NaN,5.6277,NaN,3.3623,8.9900,NaN,0.0,0.0
49168,471,12-11-2016 00:00,19-11-2016 00:00,21959,1,9,SO70377,3.0,1.0,63.5000,...,63.5000,0.0,NaN,39.7510,NaN,23.7490,63.5000,NaN,0.0,0.0
49169,477,12-11-2016 00:00,19-11-2016 00:00,21959,1,9,SO70377,4.0,1.0,4.9900,...,4.9900,0.0,NaN,3.1237,NaN,1.8663,4.9900,NaN,0.0,0.0
49170,231,12-11-2016 00:00,19-11-2016 00:00,12049,1,4,SO70378,1.0,1.0,49.9900,...,49.9900,0.0,NaN,11.4977,NaN,38.4923,49.9900,NaN,0.0,0.0
49171,465,12-11-2016 00:00,19-11-2016 00:00,12049,1,4,SO7037,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
budget

,Category,SubCategory,ProductName,Jan2016,Feb2016,Mar2016,Apr2016,May2016,Jun2016,July,Aug2016,Sep2016,"Oct, 2016","Nov, 2016","Dec, 2016",Grand Total,ProductKey
0,Accessories,Helmets,"Sport-100 Helmet, Red",5317,16221,16752,16552,17204,25354,17584,20409,18268,20567,25571,22106,221905,212.0
1,Accessories,Helmets,"Sport-100 Helmet, Red",5317,16221,16752,16552,17204,25354,17584,20409,18268,20567,25571,22106,221905,213.0
2,Accessories,Helmets,"Sport-100 Helmet, Red",5317,16221,16752,16552,17204,25354,17584,20409,18268,20567,25571,22106,221905,214.0
3,Accessories,Helmets,"Sport-100 Helmet, Red",5317,16221,16752,16552,17204,25354,17584,20409,18268,20567,25571,22106,221905,212.0
4,Accessories,Helmets,"Sport-100 Helmet, Red",5317,16221,16752,16552,17204,25354,17584,20409,18268,20567,25571,22106,221905,213.0
5,Accessories,Helmets,"Sport-100 Helmet, Red",5317,16221,16752,16552,17204,25354,17584,20409,18268,20567,25571,22106,221905,214.0
6,Accessories,Helmets,"Sport-100 Helmet, Red",5317,16221,16752,16552,17204,25354,17584,20409,18268,20567,25571,22106,221905,212.0
7,Accessories,Helmets,"Sport-100 Helmet, Red",5317,16221,16752,16552,17204,25354,17584,20409,18268,20567,25571,22106,221905,213.0
8,Accessories,Helmets,"Sport-100 Helmet, Red",5317,16221,16752,16552,17204,25354,17584,20409,18268,20567,25571,22106,221905,214.0
9,Clothing,Socks,"Mountain Bike Socks, M",24,244,432,547,385,372,839,487,425,335,660,699,5449,218.0
10,Clothing,Caps,AWC Logo Cap,479,1695,1462,1079,1729,2180,1588,2065,2013,2138,1830,2113,20371,223.0
11,Clothing,Caps,AWC Logo Cap,479,1695,1462,1079,1729,2180,1588,2065,2013,2138,1830,2113,20371,224.0
12,Clothing,Caps,AWC Logo Cap,479,1695,1462,1079,1729,2180,1588,2065,2013,2138,1830,2113,20371,225.0
13,Clothing,Caps,AWC Logo Cap,479,1695,1462,1079,1729,2180,1588,2065,2013,2138,1830,2113,20371,223.0
14,Clothing,Caps,AWC Logo Cap,479,1695,1462,1079,1729,2180,1588,2065,2013,2138,1830,2113,20371,224.0
15,Clothing,Caps,AWC Logo Cap,479,1695,1462,1079,1729,2180,1588,2065,2013,2138,1830,2113,20371,225.0
16,Clothing,Caps,AWC Logo Cap,479,1695,1462,1079,1729,2180,1588,2065,2013,2138,1830,2113,20371,223.0
17,Clothing,Caps,AWC Logo Cap,479,1695,1462,1079,1729,2180,1588,2065,2013,2138,1830,2113,20371,224.0
18,Clothing,Caps,AWC Logo Cap,479,1695,1462,1079,1729,2180,1588,2065,2013,2138,1830,2113,20371,225.0
19,Clothing,Jerseys,"Long-Sleeve Logo Jersey, S",4087,11508,12872,11809,12789,18153,16846,13497,15988,15920,17426,20043,170938,226.0
20,Clothing,Jerseys,"Long-Sleeve Logo Jersey, S",4087,11508,12872,11809,12789,18153,16846,13497,15988,15920,17426,20043,170938,227.0
21,Clothing,Jerseys,"Long-Sleeve Logo Jersey, S",4087,11508,12872,11809,12789,18153,16846,13497,15988,15920,17426,20043,170938,228.0
22,Clothing,Jerseys,"Long-Sleeve Logo Jersey, S",4087,11508,12872,11809,12789,18153,16846,13497,15988,15920,17426,20043,170938,226.0
23,Clothing,Jerseys,"Long-Sleeve Logo Jersey, S",4087,11508,12872,11809,12789,18153,16846,13497,15988,15920,17426,20043,170938,227.0
24,Clothing,Jerseys,"Long-Sleeve Logo Jersey, S",4087,11508,12872,11809,12789,18153,16846,13497,15988,15920,17426,20043,170938,228.0
25,Clothing,Jerseys,"Long-Sleeve Logo Jersey, S",4087,11508,12872,11809,12789,18153,16846,13497,15988,15920,17426,20043,170938,226.0
26,Clothing,Jerseys,"Long-Sleeve Logo Jersey, S",4087,11508,12872,11809,12789,18153,16846,13497,15988,15920,17426,20043,170938,227.0
27,Clothing,Jerseys,"Long-Sleeve Logo Jersey, S",4087,11508,12872,11809,12789,18153,16846,13497,15988,15920,17426,20043,170938,228.0
28,Bikes,Road Bikes,"Road-150 Red, 62",346295,289524,355097,346783,399691,546092,441037,432400,468572,483913,558232,590261,5257897,310.0
29,Bikes,Mountain Bikes,"Mountain-100 Silver, 38",370105,326786,384811,439822,458523,619456,524348,647048,557368,615032,802831,788234,6534364,344.0
30,Clothing,Shorts,"Men's Sports Shorts, S",421,5723,7301,6335,5288,6829,4617,5384,6277,6337,6300,7641,68453,445.0
31,Clothing,Gloves,"Half-Finger Gloves, S",598,2474,2957,2705,2819,2966,2975,3264,2424,3181,3518,4084,33965,462.0
32,Clothing,Gloves,"Half-Finger Gloves, S",598,2474,2957,2705,2819,2966,2975,3264,2424,3181,3518,4084,33965,463.0
33,Clothing,Gloves,"Half-Finger Gloves, S",598,2474,2957,2705,2819,2966,2975,3264,2424,3181,3518,4084,33965,462.0
34,Clothing,Gloves,"Half-Finger Gloves, S",598,2474,2957,2705,2819,2966,2975,3264,2424,3181,3518,4084,33965,463.0
35,Clothing,Vests,"Classic Vest, S",980,2008,1980,2312,2763,2591,3379,3580,3600,4248,3685,3439,34565,471.0
36,Accessories,Bottles and Cages,Water Bottle - 30 oz.,1892,4727,3656,4449,4051,6257,4871,5231,5461,5529,5220,6025,57369,477.0
37,Accessories,Tires and Tubes,Patch Kit/8 Patches,3554,18758,20905,18046,21680,22456,23995,22922,20950,21905,24019,23587,242777,480.0
38,Accessories,Bike Racks,Hitch Rack - 4-Bike,1131,2635,4134,2179,2637,3279,2218,3287,3885,2484,5441,3551,36861,483.0
39,Accessories,Cleaners,Bike Wash - Dissolver,160,713,555,656,369,582,777,777,239,496,686,455,6465,484.0
40,Accessories,Fenders,Fender Set - Mountain,970,3014,2809,4259,3638,3721,4190,3618,3975,3892,4740,4844,43670,485.0
41,Accessories,Bike Stands,All-Purpose Bike Stand,666,3695,2868,4862,3439,4612,2774,3003,2401,4413,3881,2143,38757,486.0
42,Accessories,Hydration Packs,Hydration Pack - 70 oz.,809,2684,2917,3425,2716,3260,3773,3523,4252,3111,4985,4348,39803,487.0
43,Bikes,Touring Bikes,"Touring-2000 Blue, 60",133631,165941,178287,265901,286630,445270,299106,407069,391580,481316,506411,494823,4055965,560.0
44,SubTotal Accessories,NaN,NaN,14499,52447,54596,54428,55734,69521,60182,62770,59431,62397,74543,67059,687607,NaN
45,SubTotal Bikes,NaN,NaN,850031,782251,918195,1052506,1144844,1610818,1264491,1486517,1417520,1580261,1867474,1873318,15848226,NaN
46,SubTotal Clothing,NaN,NaN,6589,23652,27004,24787,25773,33091,30244,28277,30727,32159,33419,38019,333741,NaN
47,Grand Total,NaN,NaN,871119,858350,999795,1131721,1226351,1713430,1354917,1577564,1507678,1674817,1975436,1978396,16869574,NaN

# **Data cleaning**

## `Dropping irrevalent columns`

- Not all the columns are important to us in the given dataframe, and hence we would drop the columns that are irrevalent to us.

In [8]:
sales = sales[['ProductKey',
 'OrderDate',
 'ShipDate',
 'CustomerKey',
 'SalesTerritoryKey',
 'SalesOrderNumber',
 'SalesOrderLineNumber',
 'OrderQuantity',
 'UnitPrice',
 'TotalProductCost',
 'SalesAmount',
 'TaxAmt',
 'Total sales revenue',
 'Gross Profit ']]

## `Renaming Columns`

In [9]:
sales = sales.rename(columns={'TaxAmt':"TaxAmount",'Total sales revenue':"TotalSalesRevenue",'Gross Profit':"GrossProfit"})

## `Changing the datatype`

- After removing the irrelavant columns, we need to ensure the data types for the columns as it should be. <br>
Checking the datatypes of the revised columns.

- changing the `dtype` of the columns wherever neccesary.

In [11]:
sales['OrderDate'] = pd.to_datetime(sales['OrderDate'],format='mixed')

In [12]:
sales['ShipDate'] = pd.to_datetime(sales['ShipDate'],format='mixed')

In [15]:
sales.dtypes

ProductKey                       int64
OrderDate               datetime64[ns]
ShipDate                datetime64[ns]
CustomerKey                      int64
SalesTerritoryKey                int64
SalesOrderNumber                object
SalesOrderLineNumber           float64
OrderQuantity                  float64
UnitPrice                      float64
TotalProductCost               float64
SalesAmount                    float64
TaxAmount                      float64
TotalSalesRevenue              float64
Gross Profit                   float64
dtype: object

In [23]:
sales.duplicated() == True

0        False
1        False
2        False
3        False
4        False
         ...
49167    False
49168    False
49169    False
49170    False
49171    False
Length: 49172, dtype: bool

# **Variance**

In [16]:
sales_2016_df = sales[sales['OrderDate'].dt.year == 2016]

In [17]:
sales_2016_df

,ProductKey,OrderDate,ShipDate,CustomerKey,SalesTerritoryKey,SalesOrderNumber,SalesOrderLineNumber,OrderQuantity,UnitPrice,TotalProductCost,SalesAmount,TaxAmount,TotalSalesRevenue,Gross Profit
5428,380,2016-01-01,2016-08-01,18239,9,SO51176,1.0,1.0,2443.35,1554.9479,2443.35,195.4680,2443.35,888.4021
5429,479,2016-01-01,2016-08-01,18239,9,SO51176,2.0,1.0,8.99,3.3623,8.99,0.7192,8.99,5.6277
5430,577,2016-01-01,2016-08-01,27873,9,SO51177,1.0,1.0,1214.85,755.1508,1214.85,97.1880,1214.85,459.6992
5431,217,2016-01-01,2016-08-01,27873,9,SO51177,2.0,1.0,34.99,13.0863,34.99,2.7992,34.99,21.9037
5432,353,2016-01-01,2016-08-01,11245,8,SO51178,1.0,1.0,2319.99,1265.6195,2319.99,185.5992,2319.99,1054.3705
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49167,479,2016-12-11,2016-11-19,21959,9,SO70377,2.0,1.0,8.99,3.3623,8.99,0.7192,8.99,5.6277
49168,471,2016-12-11,2016-11-19,21959,9,SO70377,3.0,1.0,63.50,23.7490,63.50,5.0800,63.50,39.7510
49169,477,2016-12-11,2016-11-19,21959,9,SO70377,4.0,1.0,4.99,1.8663,4.99,0.3992,4.99,3.1237
49170,231,2016-12-11,2016-11-19,12049,4,SO70378,1.0,1.0,49.99,38.4923,49.99,3.9992,49.99,11.4977
49171,465,2016-12-11,2016-11-19,12049,4,SO7037,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## **New Table**

Creating a New Table by merging Budget and Sales

In [29]:
merged_df = pd.merge(sales_2016_df, budget, on='ProductKey')

In [30]:
merged_df

,ProductKey,OrderDate,ShipDate,CustomerKey,SalesTerritoryKey,SalesOrderNumber,SalesOrderLineNumber,OrderQuantity,UnitPrice,TotalProductCost,...,Apr2016,May2016,Jun2016,July,Aug2016,Sep2016,"Oct, 2016","Nov, 2016","Dec, 2016",Grand Total
0,477,2016-01-01,2016-08-01,11245,8,SO51178,3.0,1.0,4.99,1.8663,...,4449,4051,6257,4871,5231,5461,5529,5220,6025,57369
1,477,2016-01-01,2016-08-01,16313,8,SO51180,3.0,1.0,4.99,1.8663,...,4449,4051,6257,4871,5231,5461,5529,5220,6025,57369
2,477,2016-02-01,2016-09-01,12390,8,SO51191,3.0,1.0,4.99,1.8663,...,4449,4051,6257,4871,5231,5461,5529,5220,6025,57369
3,477,2016-02-01,2016-09-01,18906,9,SO51196,3.0,1.0,4.99,1.8663,...,4449,4051,6257,4871,5231,5461,5529,5220,6025,57369
4,477,2016-02-01,2016-09-01,11448,9,SO51197,3.0,1.0,4.99,1.8663,...,4449,4051,6257,4871,5231,5461,5529,5220,6025,57369
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21840,483,2016-08-11,2016-11-15,17543,4,SO70136,2.0,1.0,120.00,44.8800,...,2179,2637,3279,2218,3287,3885,2484,5441,3551,36861
21841,483,2016-09-11,2016-11-16,17156,4,SO70221,4.0,2.0,60.00,44.8800,...,2179,2637,3279,2218,3287,3885,2484,5441,3551,36861
21842,483,2016-10-11,2016-11-17,12409,4,SO70249,1.0,4.0,30.00,44.8800,...,2179,2637,3279,2218,3287,3885,2484,5441,3551,36861
21843,483,2016-11-11,2016-11-18,12146,4,SO70312,2.0,1.0,120.00,44.8800,...,2179,2637,3279,2218,3287,3885,2484,5441,3551,36861
21844,483,2016-11-11,2016-11-18,13675,10,SO70346,4.0,1.0,120.00,44.8800,...,2179,2637,3279,2218,3287,3885,2484,5441,3551,36861

## **Data Understanding**

In [31]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21845 entries, 0 to 21844
Data columns (total 30 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ProductKey            21845 non-null  int64
 1   OrderDate             21845 non-null  datetime64[ns]
 2   ShipDate              21845 non-null  datetime64[ns]
 3   CustomerKey           21845 non-null  int64
 4   SalesTerritoryKey     21845 non-null  int64
 5   SalesOrderNumber      21845 non-null  object
 6   SalesOrderLineNumber  21845 non-null  float64
 7   OrderQuantity         21845 non-null  float64
 8   UnitPrice             21845 non-null  float64
 9   TotalProductCost      21845 non-null  float64
 10  SalesAmount           21845 non-null  float64
 11  TaxAmount             21845 non-null  float64
 12  TotalSalesRevenue     21845 non-null  float64
 13  Gross Profit          21845 non-null  float64
 14  Category              21845 non-null  object
 15  SubCategory           21845 non-null  object
 16  ProductName           21845 non-null  object
 17  Jan2016               21845 non-null  int64
 18  Feb2016               21845 non-null  int64
 19  Mar2016               21845 non-null  int64
 20  Apr2016               21845 non-null  int64
 21  May2016               21845 non-null  int64
 22  Jun2016               21845 non-null  int64
 23  July                  21845 non-null  int64
 24  Aug2016               21845 non-null  int64
 25  Sep2016               21845 non-null  int64
 26  Oct, 2016             21845 non-null  int64
 27  Nov, 2016             21845 non-null  int64
 28  Dec, 2016             21845 non-null  int64
 29  Grand Total           21845 non-null  int64
dtypes: datetime64[ns](2), float64(8), int64(16), object(4)
memory usage: 5.0+ MB

## **Check For Null/ Duplicated Values**

In [32]:
merged_df.isnull().sum()

ProductKey              0
OrderDate               0
ShipDate                0
CustomerKey             0
SalesTerritoryKey       0
SalesOrderNumber        0
SalesOrderLineNumber    0
OrderQuantity           0
UnitPrice               0
TotalProductCost        0
SalesAmount             0
TaxAmount               0
TotalSalesRevenue       0
Gross Profit            0
Category                0
SubCategory             0
ProductName             0
Jan2016                 0
Feb2016                 0
Mar2016                 0
Apr2016                 0
May2016                 0
Jun2016                 0
July                    0
Aug2016                 0
Sep2016                 0
Oct, 2016               0
Nov, 2016               0
Dec, 2016               0
Grand Total             0
dtype: int64

In [33]:
merged_df.duplicated() == True

0        False
1        False
2        False
3        False
4        False
         ...
21840    False
21841    False
21842    False
21843    False
21844    False
Length: 21845, dtype: bool

## `Dropping irrevalent columns`

- Not all the columns are important to us in the given dataframe, and hence we would drop the columns that are irrevalent to us.

In [34]:
merged_df.columns.tolist()

['ProductKey',
 'OrderDate',
 'ShipDate',
 'CustomerKey',
 'SalesTerritoryKey',
 'SalesOrderNumber',
 'SalesOrderLineNumber',
 'OrderQuantity',
 'UnitPrice',
 'TotalProductCost',
 'SalesAmount',
 'TaxAmount',
 'TotalSalesRevenue',
 'Gross Profit ',
 'Category',
 'SubCategory',
 'ProductName',
 'Jan2016',
 'Feb2016',
 'Mar2016',
 'Apr2016',
 'May2016',
 'Jun2016',
 'July',
 'Aug2016',
 'Sep2016',
 'Oct, 2016',
 'Nov, 2016',
 'Dec, 2016',
 'Grand Total']

In [36]:
merged_df = merged_df[['ProductKey',
                       'Category',
                       'SubCategory',
                       'ProductName',
                       'OrderDate',
                       'SalesAmount',
                       'ProductName',
                       'Grand Total']]

In [37]:
merged_df

,ProductKey,Category,SubCategory,ProductName,OrderDate,SalesAmount,ProductName,Grand Total
0,477,Accessories,Bottles and Cages,Water Bottle - 30 oz.,2016-01-01,4.99,Water Bottle - 30 oz.,57369
1,477,Accessories,Bottles and Cages,Water Bottle - 30 oz.,2016-01-01,4.99,Water Bottle - 30 oz.,57369
2,477,Accessories,Bottles and Cages,Water Bottle - 30 oz.,2016-02-01,4.99,Water Bottle - 30 oz.,57369
3,477,Accessories,Bottles and Cages,Water Bottle - 30 oz.,2016-02-01,4.99,Water Bottle - 30 oz.,57369
4,477,Accessories,Bottles and Cages,Water Bottle - 30 oz.,2016-02-01,4.99,Water Bottle - 30 oz.,57369
...,...,...,...,...,...,...,...,...
21840,483,Accessories,Bike Racks,Hitch Rack - 4-Bike,2016-08-11,120.00,Hitch Rack - 4-Bike,36861
21841,483,Accessories,Bike Racks,Hitch Rack - 4-Bike,2016-09-11,120.00,Hitch Rack - 4-Bike,36861
21842,483,Accessories,Bike Racks,Hitch Rack - 4-Bike,2016-10-11,120.00,Hitch Rack - 4-Bike,36861
21843,483,Accessories,Bike Racks,Hitch Rack - 4-Bike,2016-11-11,120.00,Hitch Rack - 4-Bike,36861
21844,483,Accessories,Bike Racks,Hitch Rack - 4-Bike,2016-11-11,120.00,Hitch Rack - 4-Bike,36861

## **`Calculating Variance`**

In [38]:
merged_df['Variance'] = merged_df['SalesAmount'] - merged_df['Grand Total']

In [39]:
merged_df

,ProductKey,Category,SubCategory,ProductName,OrderDate,SalesAmount,ProductName,Grand Total,Variance
0,477,Accessories,Bottles and Cages,Water Bottle - 30 oz.,2016-01-01,4.99,Water Bottle - 30 oz.,57369,-57364.01
1,477,Accessories,Bottles and Cages,Water Bottle - 30 oz.,2016-01-01,4.99,Water Bottle - 30 oz.,57369,-57364.01
2,477,Accessories,Bottles and Cages,Water Bottle - 30 oz.,2016-02-01,4.99,Water Bottle - 30 oz.,57369,-57364.01
3,477,Accessories,Bottles and Cages,Water Bottle - 30 oz.,2016-02-01,4.99,Water Bottle - 30 oz.,57369,-57364.01
4,477,Accessories,Bottles and Cages,Water Bottle - 30 oz.,2016-02-01,4.99,Water Bottle - 30 oz.,57369,-57364.01
...,...,...,...,...,...,...,...,...,...
21840,483,Accessories,Bike Racks,Hitch Rack - 4-Bike,2016-08-11,120.00,Hitch Rack - 4-Bike,36861,-36741.00
21841,483,Accessories,Bike Racks,Hitch Rack - 4-Bike,2016-09-11,120.00,Hitch Rack - 4-Bike,36861,-36741.00
21842,483,Accessories,Bike Racks,Hitch Rack - 4-Bike,2016-10-11,120.00,Hitch Rack - 4-Bike,36861,-36741.00
21843,483,Accessories,Bike Racks,Hitch Rack - 4-Bike,2016-11-11,120.00,Hitch Rack - 4-Bike,36861,-36741.00
21844,483,Accessories,Bike Racks,Hitch Rack - 4-Bike,2016-11-11,120.00,Hitch Rack - 4-Bike,36861,-36741.00

In [40]:
merged_df['Variance'].sum()

-2695040176.2799997